// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

int valor = 0;

void cliqueNaTela(lv_event_t *e)
{
    valor++;
    char str[20];
    lv_snprintf(str, sizeof(str), "%d", valor);
    _ui_label_set_property(ui_Label3, _UI_LABEL_PROPERTY_TEXT, str);
}

void buttonOkPressed(lv_event_t *e)
{
    valor++;
    char str[20];
    lv_snprintf(str, sizeof(str), "%d", valor);
    _ui_label_set_property(ui_Label3, _UI_LABEL_PROPERTY_TEXT, str);
}
